[project]
name = "teamcity-python-tests"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pytest",
    "allure-pytest",
    "requests",
    "exceptiongroup",
    "typing-extensions",
]
